const fs = require('fs');

const STAR5 = '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>';
const STAR48 = '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star-half-stroke"></i>';
const STAR4 = '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i>';
const STAR49 = STAR5;

const icons = ['fa-droplet','fa-leaf','fa-spa','fa-sun'];

function bHtml(items) {
  return items.map(t => `<li><i class="fa-solid fa-check"></i> ${t}</li>`).join('');
}
function ingHtml(items) {
  return items.map(([n,d],i) => `<li><div class="pdp-ingredient-icon"><i class="fa-solid ${icons[i%4]}"></i></div><div class="pdp-ingredient-info"><strong>${n}</strong><span>${d}</span></div></li>`).join('');
}
function stHtml(items) { return items.map(s => `<li>${s}</li>`).join(''); }
function spHtml(items) { return items.map(([k,v]) => `<li><span class="pdp-specs-label">${k}</span><span class="pdp-specs-value">${v}</span></li>`).join(''); }

const SOAP_SPECS = [["Weight","100g"],["Skin Type","All Skin Types"],["Shelf Life","12 Months"],["Made In","India"],["Paraben Free","Yes"],["Sulphate Free","Yes"],["Cruelty Free","Yes"]];
const SOAP_STEPS = ["Wet your skin with warm water","Lather the bar between your palms","Massage gently onto face and body in circular motions","Rinse thoroughly with water","Use twice daily for best results"];

const products = [
  {file:"product-red-wine.html",title:"Red Wine Soap",badge:"Premium",img:"product_red_wine.png",category:"Radiance",price:"399",rating:"4.8",stars:STAR48,dataName:"Red Wine Soap",metaDesc:"Rich in antioxidants from real red wine extract for youthful, glowing skin.",desc:"Rich in antioxidants from real red wine extract for youthful, glowing skin. This premium bar harnesses the power of resveratrol and natural polyphenols to fight aging, boost collagen, and reveal a luminous, wine-kissed glow.",benefits:["Powerful antioxidants from real red wine fight free radicals and premature aging","Resveratrol boosts collagen production for firmer, youthful skin","Gentle exfoliation removes dead cells revealing fresh, glowing skin","Natural polyphenols improve blood circulation for a healthy, rosy complexion"],ingredients:[["Red Wine Extract","Rich in resveratrol and antioxidants for anti-aging"],["Grape Seed Oil","Powerful antioxidant that tightens and firms skin"],["Vitamin E","Protects skin cells from environmental damage"],["Glycerin","Natural humectant for lasting moisture"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-neem.html",title:"Neem Purify",badge:"Organic",img:"product_neem.png",category:"Healing",price:"399",rating:"4.0",stars:STAR4,dataName:"Neem Purify",metaDesc:"Deep cleansing antibacterial neem and tea tree oil for problem skin.",desc:"Deep cleansing antibacterial neem and tea tree oil for problem skin. This powerful Ayurvedic formula targets acne, blemishes, and excess oil while preserving your skin\u2019s natural moisture balance.",benefits:["Powerful antibacterial and antifungal properties fight acne-causing bacteria","Deep cleanses pores and removes excess oil without over-drying","Ancient Ayurvedic healing reduces inflammation and soothes irritated skin","Tea tree oil provides additional antiseptic protection for clear skin"],ingredients:[["Neem Extract","Centuries-old Ayurvedic antiseptic for purification"],["Tea Tree Oil","Natural antibacterial and antifungal agent"],["Turmeric","Anti-inflammatory that soothes redness"],["Aloe Vera","Cooling hydration that calms and heals"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-soapnut.html",title:"Soap Nut Power",badge:"Ayurvedic",img:"product_soapnut.png",category:"Healing",price:"100",rating:"4.5",stars:STAR48,dataName:"Soap Nut Power",metaDesc:"Ancient reetha cleanser with natural saponins for gentle, chemical-free cleansing.",desc:"Ancient reetha cleanser with natural saponins for gentle, chemical-free cleansing and silky skin. This traditional Ayurvedic bar uses the power of soap nuts to create a naturally foaming, ultra-gentle cleanse.",benefits:["Natural saponins create a gentle, chemical-free cleansing foam","Perfect for sensitive skin \u2014 no harsh detergents or synthetic surfactants","Mild yet effective cleansing preserves skin\u2019s natural oils and pH","Ancient Ayurvedic ingredient trusted for centuries for skin care"],ingredients:[["Soap Nut (Reetha)","Natural saponin-rich cleanser from the Sapindus tree"],["Coconut Oil","Deep moisture and protective barrier"],["Neem Oil","Antibacterial protection for healthy skin"],["Glycerin","Locks in moisture for soft, supple skin"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-seegekai.html",title:"Seegekai",badge:"Herbal",img:"product_shikakai.png",category:"Healing",price:"399",rating:"4.0",stars:STAR4,dataName:"Seegekai",metaDesc:"Traditional shikakai-infused bar for deep cleansing, scalp care, and natural herbal shine.",desc:"Traditional shikakai-infused bar for deep cleansing, scalp care, and a natural herbal shine. This heritage formula combines Seegekai with complementary herbs for a complete head-to-toe cleansing ritual.",benefits:["Shikakai naturally cleanses hair and scalp without stripping oils","Strengthens hair roots and reduces hairfall with regular use","Creates a gentle lather suitable for daily use on hair and body","Traditional herbal formula adds natural shine and volume"],ingredients:[["Shikakai (Seegekai)","Traditional herb for hair and scalp health"],["Amla","Vitamin C rich for strong, lustrous hair"],["Reetha","Natural foaming agent for gentle cleansing"],["Bhringraj","King of herbs for hair growth and thickness"]],steps:["Wet your hair and body with warm water","Rub the bar directly on wet hair or lather between hands","Massage into scalp and through hair, then onto body","Leave for 1-2 minutes for extra nourishment","Rinse thoroughly with water"],specs:SOAP_SPECS},
  {file:"product-besan.html",title:"Besan",badge:"Glow",img:"product_besan.png",category:"Radiance",price:"109",rating:"5.0",stars:STAR5,dataName:"Besan",metaDesc:"Traditional gram flour face and body bar for radiant complexion.",desc:"Traditional gram flour face and body bar for a radiant complexion and smooth, exfoliated skin. This ancient beauty secret combines the power of besan with botanical oils for a gentle yet effective glow-boosting cleanse.",benefits:["Natural gentle exfoliation removes dead skin for instant brightness","Gram flour absorbs excess oil and tightens pores","Traditional Indian beauty ingredient for a natural golden glow","Rich in proteins and minerals that nourish and strengthen skin"],ingredients:[["Besan (Gram Flour)","Natural exfoliant and skin brightener"],["Turmeric","Golden spice for radiance and even tone"],["Sandalwood Powder","Cooling agent that soothes and brightens"],["Rose Water","Natural toner that hydrates and balances pH"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-bath-salts.html",title:"Relaxing Bath Salts",badge:"Calming",img:"relaxing_bath_salts.png",category:"Calming",price:"199",rating:"5.0",stars:STAR5,dataName:"Relaxing Bath Salts",metaDesc:"Epsom and Pink Salt bath soak for muscle recovery and stress relief.",desc:"Epsom and Pink Salt bath soak for muscle recovery, stress relief, and better sleep. Dissolve these therapeutic salts in warm water for a luxurious spa experience that soothes tired muscles and calms the mind.",benefits:["Epsom salt relieves muscle tension, aches, and post-workout soreness","Pink Himalayan salt detoxifies and draws out impurities from skin","Aromatherapy blend promotes deep relaxation and better sleep quality","Mineral-rich formula softens and hydrates skin while you soak"],ingredients:[["Epsom Salt","Magnesium-rich for muscle relaxation and recovery"],["Pink Himalayan Salt","84+ trace minerals for detoxification"],["Lavender Essential Oil","Calming aromatherapy for stress relief"],["Eucalyptus Oil","Refreshing and respiratory-clearing"]],steps:["Fill your bathtub with warm water (37-40\u00B0C)","Add 2-3 tablespoons of bath salts to the running water","Stir gently until salts are fully dissolved","Soak for 15-20 minutes for full therapeutic benefit","Pat dry and moisturize after your bath"],specs:[["Weight","250g"],["Type","Bath Soak"],["Shelf Life","24 Months"],["Made In","India"],["Chemical Free","Yes"],["Cruelty Free","Yes"]]},
  {file:"product-loofah.html",title:"Loofah Body Scrubber",badge:"Eco",img:"product_loofah.png",category:"Radiance",price:"50",rating:"4.8",stars:STAR48,dataName:"Loofah Body Scrubber",metaDesc:"Natural exfoliating bath sponge for smooth, glowing skin. 100% biodegradable.",desc:"Natural exfoliating bath sponge for smooth, glowing skin. This 100% biodegradable loofah gently removes dead skin cells, improves circulation, and leaves your skin velvety smooth and radiant.",benefits:["Natural exfoliation removes dead skin cells for a smooth complexion","Improves blood circulation and lymphatic drainage during use","100% biodegradable and eco-friendly \u2014 zero plastic waste","Long-lasting and easy to clean \u2014 naturally antimicrobial"],ingredients:[["Natural Loofah Fiber","Sustainably harvested from Luffa cylindrica plant"],["No Chemicals","100% unprocessed natural sponge"],["Biodegradable","Composts completely after use"],["Eco-Friendly","Zero plastic packaging"]],steps:["Soak the loofah in warm water for 2-3 minutes to soften","Apply your favorite soap or body wash onto the loofah","Scrub gently in circular motions starting from feet upward","Rinse thoroughly and squeeze out excess water","Hang to dry in a well-ventilated area after each use"],specs:[["Material","Natural Loofah"],["Size","Medium"],["Shelf Life","2-3 Months"],["Made In","India"],["Biodegradable","Yes"],["Plastic Free","Yes"]]},
  {file:"product-bamboo-toothbrush.html",title:"Bamboo Toothbrush",badge:"Eco",img:"product_bamboo_toothbrush.png",category:"Oral Care",price:"70",rating:"4.9",stars:STAR5,dataName:"Bamboo Toothbrush",metaDesc:"Eco-friendly sustainable toothbrush with charcoal infused soft bristles.",desc:"Eco-friendly sustainable toothbrush with charcoal-infused soft bristles. This premium bamboo toothbrush offers superior cleaning while reducing plastic waste \u2014 one small swap for a greener planet.",benefits:["Charcoal-infused bristles naturally whiten teeth over time","Sustainably sourced bamboo handle \u2014 100% biodegradable","Soft, rounded bristles are gentle on gums and enamel","Naturally antimicrobial \u2014 bamboo resists bacterial growth"],ingredients:[["Moso Bamboo","Sustainably harvested, fast-growing bamboo handle"],["Charcoal Bristles","Activated charcoal for natural whitening"],["BPA-Free Nylon","Soft, rounded tips for gentle cleaning"],["Natural Finish","Water-based sealant on handle"]],steps:["Wet the bristles under running water","Apply a pea-sized amount of toothpaste","Brush gently in circular motions for 2 minutes","Rinse brush and store upright to air dry","Replace every 2-3 months or when bristles fray"],specs:[["Material","Moso Bamboo + Charcoal Nylon"],["Bristle Type","Soft"],["Shelf Life","2-3 Months"],["Made In","India"],["BPA Free","Yes"],["Biodegradable Handle","Yes"]]},
  {file:"product-seegekai-powder.html",title:"Seegekai Powder",badge:"Ayurvedic",img:"product_seegekai_powder.png",category:"Hair Care",price:"249",rating:"4.7",stars:STAR48,dataName:"Seegekai Powder",metaDesc:"Pure organic hair wash powder for strong roots and reduced hairfall.",desc:"Pure organic Seegekai hair wash powder for strong roots, reduced hairfall, and natural shine. This 100% natural alternative to chemical shampoos gently cleanses while nourishing your scalp.",benefits:["Naturally cleanses hair without harsh sulphates or chemicals","Strengthens hair roots and significantly reduces hairfall","Promotes natural shine, volume, and silky texture","Soothes scalp irritation, dandruff, and dryness"],ingredients:[["Shikakai Powder","Natural hair cleanser rich in vitamins A, C, D, E, K"],["Amla Powder","Iron and Vitamin C for hair strength"],["Reetha Powder","Natural foaming agent for gentle wash"],["Hibiscus Powder","Promotes hair growth and prevents premature graying"]],steps:["Mix 2-3 tablespoons of powder with water to form a paste","Apply evenly to wet hair and scalp","Massage gently into the scalp for 3-5 minutes","Leave on for 5 minutes for deep conditioning","Rinse thoroughly with water \u2014 no conditioner needed"],specs:[["Weight","100g"],["Type","Hair Wash Powder"],["Shelf Life","18 Months"],["Made In","India"],["Chemical Free","Yes"],["Sulphate Free","Yes"]]},
  {file:"product-hotel-soaps.html",title:"Hotel Soaps",badge:"Premium",img:"product_hotel_soaps.png",category:"Gift Set",price:"599",rating:"4.9",stars:STAR5,dataName:"Hotel Soaps",metaDesc:"Luxury miniature botanical soap set for hotels, resorts, and gifting.",desc:"Luxury miniature botanical soap set, perfect for hotels, resorts, and gifting. This curated collection of artisan soaps features our finest formulations in elegant, travel-friendly sizes.",benefits:["Curated assortment of our finest botanical soap varieties","Perfect size for travel, hotels, resorts, and guest bathrooms","Elegant eco-friendly packaging makes it an ideal gift","Each bar crafted with the same premium natural ingredients"],ingredients:[["Mixed Botanicals","Curated selection of our finest formulations"],["Essential Oils","Therapeutic-grade aromatherapy blends"],["Shea Butter","Rich moisturizing base across all varieties"],["Natural Glycerin","Gentle cleansing with lasting hydration"]],steps:["Choose your preferred soap variant for the occasion","Wet your hands and lather the bar with warm water","Enjoy the unique botanical fragrance of each variety","Rinse and pat dry","Store unused bars in a cool, dry place"],specs:[["Weight","6 x 30g bars"],["Type","Gift Set"],["Shelf Life","12 Months"],["Made In","India"],["Paraben Free","Yes"],["Eco Packaging","Yes"]]},
  {file:"product-coffee.html",title:"Exfoliating Coffee Soap",badge:"Exfoliating",img:"product_coffee_soap.png",category:"Radiance",price:"149",rating:"4.8",stars:STAR48,dataName:"Exfoliating Coffee Soap",metaDesc:"Rich roasted coffee granules for deep exfoliation and cellulite reduction.",desc:"Rich roasted coffee granules for deep exfoliation and cellulite reduction. This energizing bar combines freshly ground Arabica coffee with moisturizing oils to buff away dead skin and reveal smooth, toned, radiant skin.",benefits:["Coffee granules provide powerful physical exfoliation for smooth skin","Caffeine stimulates blood flow and helps reduce cellulite appearance","Antioxidant-rich formula fights aging and environmental damage","Energizing coffee aroma provides a natural morning boost"],ingredients:[["Arabica Coffee Grounds","Fresh-ground for effective natural exfoliation"],["Coconut Oil","Deep moisture and skin barrier protection"],["Cocoa Butter","Rich emollient for silky-smooth skin"],["Vitamin E","Antioxidant protection from free radicals"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-rice-goat-milk.html",title:"Rice Goat Milk Soap",badge:"Premium",img:"product_rice_goat_milk.png",category:"Hydrating",price:"149",rating:"4.8",stars:STAR48,dataName:"Rice Goat Milk Soap",metaDesc:"Rich in vitamins and lactic acid to gently exfoliate and deeply moisturize.",desc:"Rich in vitamins and lactic acid to gently exfoliate and deeply moisturize for glass-like glowing skin. This luxurious combination of rice bran and goat milk creates an incredibly nourishing cleanse.",benefits:["Lactic acid from goat milk gently exfoliates for glass-like skin","Rice bran oil provides deep hydration and brightening","Natural vitamins A, D, and B6 nourish skin from within","Creamy lather soothes and repairs dry, damaged skin"],ingredients:[["Goat Milk","Rich in lactic acid, vitamins, and minerals"],["Rice Bran Oil","Antioxidant-rich for brightening and firming"],["Shea Butter","Deep nourishment and moisture retention"],["Honey","Natural humectant with antibacterial properties"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-multani-mitti.html",title:"Multani Mitti Soap",badge:"Purifying",img:"product_multani_mitti.png",category:"Healing",price:"109",rating:"4.7",stars:STAR48,dataName:"Multani Mitti Soap",metaDesc:"Natural Fuller\u2019s Earth to absorb impurities, reduce acne, and leave skin fresh.",desc:"Natural Fuller\u2019s Earth to absorb impurities, reduce acne, and leave skin fresh and oil-free. This deep-cleansing bar harnesses the detoxifying power of Multani Mitti clay to draw out toxins and tighten pores.",benefits:["Fuller\u2019s Earth absorbs excess oil and controls shine all day","Deep cleanses pores drawing out blackheads and impurities","Natural astringent tightens pores and firms skin texture","Anti-acne properties reduce breakouts and blemishes"],ingredients:[["Multani Mitti (Fuller\u2019s Earth)","Natural clay for deep pore cleansing"],["Neem Extract","Antibacterial protection against acne"],["Rose Water","Tones and balances skin pH naturally"],["Aloe Vera","Soothes and hydrates after deep cleansing"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
  {file:"product-charcoal.html",title:"Activated Charcoal Soap",badge:"Anti-Pollution",img:"product_charcoal.png",category:"Healing",price:"129",rating:"4.9",stars:STAR5,dataName:"Activated Charcoal Soap",metaDesc:"Deep pore detox for pollution protection. Draws out toxins for clear, healthy skin.",desc:"Deep pore detox for pollution protection. Draws out toxins and unclogs pores for clear, healthy skin. This powerful charcoal bar acts like a magnet for impurities, making it perfect for urban skin exposed to daily pollution.",benefits:["Activated charcoal draws out deep-seated toxins and impurities","Powerful anti-pollution shield protects skin from environmental damage","Unclogs pores and prevents blackheads and whiteheads","Balances oily skin without over-drying or irritating"],ingredients:[["Activated Charcoal","Ultra-fine grade for maximum toxin absorption"],["Tea Tree Oil","Antibacterial and antifungal protection"],["Bentonite Clay","Additional detoxifying and pore-cleansing power"],["Eucalyptus Oil","Refreshing and purifying aromatherapy"]],steps:SOAP_STEPS,specs:SOAP_SPECS},
];

const template = (p) => `<!DOCTYPE html>
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-5KEF8NTVQC"></script>
    <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-5KEF8NTVQC');</script>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${p.title} | Bloom Cure</title>
    <meta name="description" content="${p.metaDesc}">
    <link rel="icon" type="image/png" href="assets/favicon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,700;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/index.css"><link rel="stylesheet" href="css/product-page.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
</head>
<body>
    <div id="bc-dot"></div><div id="bc-ring"></div><div id="bc-bar"></div>
    <div class="bc-ticker" role="marquee"><div class="bc-ticker__wrap"><span class="bc-ticker__item"><b>\u2726</b> Free shipping on orders above \u20B9999</span><span class="bc-ticker__item"><b>\uD83C\uDF3F</b> 100% Natural &amp; Handcrafted</span><span class="bc-ticker__item"><b>\u2726</b> New arrivals every week</span><span class="bc-ticker__item"><b>\uD83C\uDF31</b> Zero plastic packaging</span><span class="bc-ticker__item"><b>\u2726</b> Cruelty-free &amp; Ayurvedic</span><span class="bc-ticker__item"><b>\uD83E\uDDFC</b> Small-batch artisan quality</span><span class="bc-ticker__item"><b>\u2726</b> Free shipping on orders above \u20B9999</span><span class="bc-ticker__item"><b>\uD83C\uDF3F</b> 100% Natural &amp; Handcrafted</span><span class="bc-ticker__item"><b>\u2726</b> New arrivals every week</span><span class="bc-ticker__item"><b>\uD83C\uDF31</b> Zero plastic packaging</span><span class="bc-ticker__item"><b>\u2726</b> Cruelty-free &amp; Ayurvedic</span><span class="bc-ticker__item"><b>\uD83E\uDDFC</b> Small-batch artisan quality</span></div></div>
    <nav class="premium-nav" id="mainNav"><div class="premium-nav__inner"><a href="index.html" class="premium-nav__logo"><img src="assets/logo.jpg" alt="Bloom Cure Logo"><div class="premium-nav__brand"><span class="premium-nav__brand-name">Bloom Cure</span><span class="premium-nav__brand-tagline">Artisan Botanicals</span></div></a><ul class="premium-nav__links"><li><a href="index.html" class="premium-nav__link">Home</a></li><li><a href="shop.html" class="premium-nav__link active">Shop</a></li><li><a href="about.html" class="premium-nav__link">About</a></li><li><a href="index.html#ingredients" class="premium-nav__link">Ingredients</a></li></ul><div class="premium-nav__actions"><a href="cart.html" class="premium-nav__icon-btn premium-nav__cart-btn" title="Cart"><i class="fa-solid fa-bag-shopping"></i><span id="cart-count" class="premium-nav__cart-badge">0</span></a><button class="premium-nav__icon-btn premium-nav__menu-btn" title="Menu" onclick="toggleMobileMenu()"><i class="fa-solid fa-bars"></i></button></div></div></nav>
    <section class="pdp-hero"><div class="container"><div class="pdp-grid">
        <div class="pdp-image-wrap" style="position:relative"><span class="pdp-image-badge">${p.badge}</span><img src="assets/${p.img}" alt="Bloom Cure ${p.title}"></div>
        <div class="pdp-info">
            <div class="pdp-breadcrumb"><a href="index.html">Home</a><i class="fa-solid fa-chevron-right" style="font-size:0.5rem"></i><a href="shop.html">Shop</a><i class="fa-solid fa-chevron-right" style="font-size:0.5rem"></i><span>${p.title}</span></div>
            <div class="pdp-category">${p.category}</div>
            <h1 class="pdp-title">${p.title}</h1>
            <div class="pdp-rating">${p.stars}<span>${p.rating}</span></div>
            <div class="pdp-price">\u20B9${p.price}</div>
            <div class="pdp-price-note">Inclusive of all taxes \xB7 Free shipping over \u20B9999</div>
            <p class="pdp-desc">${p.desc}</p>
            <div class="pdp-actions" data-name="${p.dataName}" data-price="${p.price}"><button class="btn-add-cart" onclick="addToCartPDP(this)"><i class="fa-solid fa-bag-shopping"></i> Add to Cart</button><button class="btn-buy-now" onclick="buyNowPDP(this)"><i class="fa-brands fa-whatsapp"></i> Buy Now</button></div>
            <div class="pdp-trust-row"><div class="pdp-trust-item"><i class="fa-solid fa-leaf"></i> 100% Natural</div><div class="pdp-trust-item"><i class="fa-solid fa-hand-sparkles"></i> Handcrafted</div><div class="pdp-trust-item"><i class="fa-solid fa-shield-halved"></i> Dermatologist Tested</div><div class="pdp-trust-item"><i class="fa-solid fa-box-open"></i> Eco Packaging</div></div>
        </div>
    </div></div></section>
    <section class="pdp-details"><div class="container"><div class="pdp-details-grid">
        <div><h2 class="pdp-section-heading"><i class="fa-solid fa-sparkles"></i> Key Benefits</h2><ul class="pdp-benefits">${bHtml(p.benefits)}</ul></div>
        <div><h2 class="pdp-section-heading"><i class="fa-solid fa-seedling"></i> Key Ingredients</h2><ul class="pdp-ingredients-list">${ingHtml(p.ingredients)}</ul></div>
    </div></div></section>
    <section class="pdp-how-specs"><div class="container"><div class="pdp-how-specs-grid">
        <div><h2 class="pdp-section-heading"><i class="fa-solid fa-hand-holding-droplet"></i> How to Use</h2><ol class="pdp-steps">${stHtml(p.steps)}</ol></div>
        <div><h2 class="pdp-section-heading"><i class="fa-solid fa-clipboard-list"></i> Specifications</h2><ul class="pdp-specs">${spHtml(p.specs)}</ul></div>
    </div></div></section>
    <footer class="site-footer"><div class="container"><div class="footer-grid"><div><a href="index.html" style="text-decoration:none"><h3 class="footer-brand">Bloom Cure</h3></a><p class="footer-brand-desc">Where every bar is a petal of health.</p></div><div><h4 class="footer-heading">Shop</h4><ul class="footer-links"><li><a href="shop.html">All Soaps</a></li><li><a href="#">Gift Bundles</a></li></ul></div><div><h4 class="footer-heading">Company</h4><ul class="footer-links"><li><a href="about.html">Our Story</a></li><li><a href="contact.html">Contact Us</a></li><li><a href="privacy.html">Privacy Policy</a></li><li><a href="terms.html">Terms of Service</a></li></ul></div><div class="footer-newsletter"><h4 class="footer-heading">Newsletter</h4><p class="footer-newsletter__desc">Join our botanical circle.</p><form class="footer-newsletter__form" onsubmit="event.preventDefault();showToast('Welcome! \uD83C\uDF3F')"><input type="email" placeholder="Email" class="footer-newsletter__input" required><button type="submit" class="footer-newsletter__btn">Join</button></form></div></div><div class="footer-bottom"><p>&copy; 2026 Bloom Cure.</p><div class="footer-socials"><a href="https://www.instagram.com/bloomcure.skincare/" target="_blank"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-pinterest"></i></a><a href="https://www.facebook.com/profile.php?id=61582243962413" target="_blank"><i class="fa-brands fa-facebook-f"></i></a></div></div></div></footer>
    <div class="mobile-menu-overlay" id="mobileMenu"><div class="mobile-menu__inner"><button class="mobile-menu__close" onclick="toggleMobileMenu()"><i class="fa-solid fa-xmark"></i></button><div class="mobile-menu__brand"><img src="assets/logo.jpg" alt="Bloom Cure"><span class="mobile-menu__brand-name">Bloom Cure</span></div><ul class="mobile-menu__links"><li><a href="index.html">Home</a></li><li><a href="shop.html" class="active">Shop</a></li><li><a href="about.html">About</a></li><li><a href="index.html#ingredients">Ingredients</a></li></ul></div></div>
    <div id="cart-toast" class="toast glass-toast" style="color:var(--clr-cream)"><i class="fa-solid fa-circle-check"></i><span></span></div>
    <script src="js/product-page.js"></script><button id="bc-top" aria-label="Back to top"><i class="fa-solid fa-arrow-up"></i></button><script src="bloom-psychology.js"></script>
</body></html>`;

products.forEach(p => {
  fs.writeFileSync(p.file, template(p), 'utf8');
  console.log('Created ' + p.file);
});
console.log('All done!');
